#!/bin/bash
mkdir QAC_will
cd QAC_will
touch file1 file2 file3
echo "some text" >> file1
echo "some text" >> file2
echo "some text" >> file3
mkdir childDir
cp ~/projects/linux-tasks/QAC_will/file{1..3} ~/projects/linux-tasks/QAC_will/childDir/

