#!/bin/bash

echo "Input Numbers: "
read -a arr

for i in ${arr[@]}; do

	if [[ "($i%3) + ($i%5)" -eq 0 ]]
	then
	    echo "FizzBuzz!"
	elif [[ "($i%3)" -eq 0 ]]
	then
	    echo "Fizz!"
	elif [[ "($i%5)" -eq 0 ]]
	then
	    echo "Buzz!"
	else
	    echo "$i"
	fi
done


